security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            id: App\Security\UserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        connect_google:
            pattern: ^/api/connect/google$
            stateless: true
            security: false

        connect_google_check:
            pattern: ^/api/connect/google/check$
            stateless: false
            security: false

        exchange_code:
            pattern: ^/api/exchange-code$
            stateless: true
            security: false

        login:
            pattern: ^/api/login$
            stateless: true
            json_login:
                check_path: /api/login
                username_path: identifier
                password_path: password
                success_handler: App\Security\CustomAuthenticationSuccessHandler
                failure_handler: App\Security\CustomAuthenticationFailureHandler

        register:
            pattern: ^/api/register$
            stateless: true
            security: false

        confirm:
            pattern: ^/api/confirm$
            stateless: true
            security: false

        forgot_password:
            pattern: ^/api/forgot-password$
            stateless: true
            security: false

        reset_password:
            pattern: ^/api/reset-password$
            stateless: true
            security: false

        api:
            pattern: ^/api
            stateless: true
            provider: app_user_provider
            jwt: ~

        check_auth:
            pattern: ^/api/check-auth$
            stateless: true
            jwt: ~

#        logout:
#            pattern: ^/api/logout
#            stateless: true
#            security: true
#            provider: app_user_provider
#            jwt: ~

        get_user:
            pattern: ^/api/get-user
            stateless: true
            security: true
            provider: app_user_provider
            jwt: ~

        get_all_users:
            pattern: ^/api/get-user
            stateless: true
            security: true
            provider: app_user_provider
            jwt: ~

        delete_user:
            pattern: ^/api/delete-user
            stateless: true
            security: true
            provider: app_user_provider
            jwt: ~

        send_delete_code:
            pattern: ^/api/send-delete-code
            stateless: true
            security: true
            provider: app_user_provider
            jwt: ~

        update_user:
            pattern: ^/api/update-user
            stateless: true
            security: true
            provider: app_user_provider
            jwt: ~



    access_control:
        - { path: ^/api/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/register$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - {path: ^/api/exchange-code$, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/api/forgot-password, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/api/reset-password, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/confirm$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/check-auth$, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/logout$, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/delete-user$, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/send-delete-code, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/update-user, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/connect$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/connect/google$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/connect/google/check$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/get-user, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/get-all-users$, roles: IS_AUTHENTICATED_FULLY }

