# config/packages/framework.yaml

framework:
    rate_limiter:
        login:
            policy: 'sliding_window'
            limit: 500
            interval: '1 minute'
            cache_pool: 'cache.login'
        registration:
            policy: 'sliding_window'
            limit: 500
            interval: '1 hour'
            cache_pool: 'cache.registration'
        forgot_password:
            policy: 'sliding_window'
            limit: 3
            interval: '1 hour'
            cache_pool: 'cache.forgot_password'
        reset_password:
            policy: 'sliding_window'
            limit: 3
            interval: '1 hour'
            cache_pool: 'cache.reset_password'
        delete_user:
            policy: 'sliding_window'
            limit: 30
            interval: '1 hour'
            cache_pool: 'cache.delete_user'
        send_code:
            policy: 'sliding_window'
            limit: 30
            interval: '1 hour'
            cache_pool: 'cache.send_code'
        update_user:
            policy: 'sliding_window'
            limit: 30
            interval: '1 hour'
            cache_pool: 'cache.update_user'
        connect_action:
            policy: 'sliding_window'
            limit: 50
            interval: '1 hour'
            cache_pool: 'cache.connect_action'
        connect_check_action:
            policy: 'sliding_window'
            limit: 50
            interval: '1 hour'
            cache_pool: 'cache.connect_check_action'
        exchange_code:
            policy: 'sliding_window'
            limit: 50
            interval: '1 hour'
            cache_pool: 'cache.exchange_code'

